name: thai-lpr-api
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch
    - torchvision
    - torchaudio
    - inference-sdk
    - tqdm
    - pillow
    - pandas
    - opencv-python
    - matplotlib
    - requests
    - editdistance
    - scikit-learn
    - fastapi
    - uvicorn
    - python-multipart